name: Deploy Testing Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create Backend .env
        shell: powershell
        run: |
          @"
          ${{ secrets.BACKEND_ENV }}
          "@ | Set-Content backend\.env

      - name: Stop Containers
        run: docker compose down

      - name: Build and Start
        run: docker compose up -d --build

      - name: Remove old images
        run: docker image prune -f
